'use client';

import { useState, useEffect } from 'react';

const DEMO_TRANSCRIPT = "Attended site at 09:30. Inspected HVAC unit A-201 on the roof. Found bearing failure on the main fan motor. Unit was making loud rattling noise. Isolated power and removed fan housing. Confirmed bearing worn and seized. Ordered replacement bearing from HVAC Parts Direct, part number BRG-6205-2RS. Estimated delivery 2 days. Temporary fix applied to reduce noise. Will return when parts arrive to complete repair. Site left safe. Spoke to facilities manager John Smith who is aware of the situation.";

const DEMO_REPORT = `**ENGINEER SITE VISIT REPORT**
*Generated by Synqoro AI Voice Reporting*

**Date:** ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
**Time of Attendance:** 09:30
**Asset:** HVAC Unit A-201 (Rooftop)

**FAULT DESCRIPTION:**
Main fan motor bearing failure causing excessive noise during operation. Unit producing loud rattling sound audible from building interior.

**WORK CARRIED OUT:**
1. Isolated electrical supply to unit
2. Removed fan housing for inspection
3. Confirmed bearing failure — bearing worn and seized
4. Applied temporary fix to reduce noise levels
5. Ordered replacement bearing (Part No: BRG-6205-2RS) from HVAC Parts Direct

**PARTS ORDERED:**
• Fan Bearing 6205-2RS × 1 — ETA 2 days

**CURRENT STATUS:**
Awaiting parts. Unit operational with temporary fix. Return visit scheduled upon parts delivery.

**CLIENT COMMUNICATION:**
Facilities Manager (John Smith) informed of situation and expected timeline.

**NEXT VISIT:**
Return to site within 2-3 days to complete bearing replacement.

*Report generated from voice note by Synqoro AI*`;

export default function AIVoiceReporting() {
  const [recording, setRecording] = useState(false);
  const [transcript, setTranscript] = useState('');
  const [report, setReport] = useState('');
  const [generating, setGenerating] = useState(false);
  const [timer, setTimer] = useState(0);

  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (recording) interval = setInterval(() => setTimer(t => t + 1), 1000);
    else setTimer(0);
    return () => clearInterval(interval);
  }, [recording]);

  const formatTimer = (s: number) => `${String(Math.floor(s / 60)).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`;

  const startRecording = () => {
    if (typeof window === 'undefined') return;
    const SR = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (SR) {
      const recognition = new SR();
      recognition.continuous = true;
      recognition.lang = 'en-GB';
      recognition.onresult = (e: any) => {
        const t = Array.from(e.results).map((r: any) => r[0].transcript).join(' ');
        setTranscript(t);
      };
      recognition.start();
      setRecording(true);
      (window as any)._aiRecognition = recognition;
    } else {
      setRecording(true);
      setTimeout(() => { setTranscript(DEMO_TRANSCRIPT); setRecording(false); }, 3000);
    }
  };

  const stopRecording = () => {
    if ((window as any)._aiRecognition) {
      (window as any)._aiRecognition.stop();
      delete (window as any)._aiRecognition;
    }
    setRecording(false);
    if (!transcript) setTranscript(DEMO_TRANSCRIPT);
  };

  const generateReport = async () => {
    setGenerating(true);
    await new Promise(r => setTimeout(r, 2000));
    setReport(DEMO_REPORT);
    setGenerating(false);
  };

  return (
    <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-8 h-8 bg-pink-100 rounded-lg flex items-center justify-center">
          <i className="ri-mic-line text-pink-600 text-sm"></i>
        </div>
        <div>
          <p className="font-semibold text-gray-800 text-sm">AI Voice Reporting</p>
          <p className="text-xs text-gray-400">Record voice notes → professional reports</p>
        </div>
      </div>

      <div className="text-center mb-4">
        <button
          onClick={recording ? stopRecording : startRecording}
          className={`w-16 h-16 rounded-full flex items-center justify-center mx-auto cursor-pointer transition-all shadow-lg ${recording ? 'bg-red-500 hover:bg-red-600 animate-pulse' : 'bg-gradient-to-br from-pink-500 to-red-500 hover:opacity-90'}`}
        >
          <i className={`${recording ? 'ri-stop-fill' : 'ri-mic-fill'} text-white text-2xl`}></i>
        </button>
        {recording && (
          <div className="mt-2 flex items-center justify-center gap-2">
            <span className="w-2 h-2 bg-red-500 rounded-full animate-pulse"></span>
            <span className="text-sm text-red-600 font-medium" suppressHydrationWarning={true}>Recording {formatTimer(timer)}</span>
          </div>
        )}
        {!recording && !transcript && <p className="text-xs text-gray-400 mt-2">Tap to start recording your voice note</p>}
      </div>

      {transcript && (
        <div className="mb-3">
          <p className="text-xs font-semibold text-gray-500 mb-1">Transcript:</p>
          <div className="bg-gray-50 rounded-xl p-3 border border-gray-100 text-xs text-gray-600 max-h-24 overflow-y-auto leading-relaxed">
            {transcript}
          </div>
          <button onClick={generateReport} disabled={generating}
            className="w-full mt-2 py-2 bg-gradient-to-r from-pink-500 to-purple-600 text-white rounded-xl text-sm font-semibold hover:opacity-90 cursor-pointer disabled:opacity-50 whitespace-nowrap">
            {generating ? <><i className="ri-loader-4-line animate-spin mr-1"></i>Generating Report...</> : <><i className="ri-sparkling-line mr-1"></i>Generate Professional Report</>}
          </button>
        </div>
      )}

      {report && (
        <div>
          <div className="flex items-center justify-between mb-1">
            <p className="text-xs font-semibold text-gray-500">Generated Report:</p>
            <button onClick={() => navigator.clipboard?.writeText(report)} className="text-xs text-blue-600 hover:text-blue-700 cursor-pointer">
              <i className="ri-file-copy-line mr-1"></i>Copy
            </button>
          </div>
          <div className="bg-blue-50 rounded-xl p-3 border border-blue-100 text-xs text-gray-700 max-h-48 overflow-y-auto leading-relaxed">
            {report.split('\n').map((line, i) => {
              const formatted = line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
              return line.trim() ? <p key={i} className="mb-0.5" dangerouslySetInnerHTML={{ __html: formatted }} /> : <div key={i} className="h-1" />;
            })}
          </div>
        </div>
      )}
    </div>
  );
}